services:
  discordbot:
    container_name: "goMuffin"
    build: "."
    env_file:
      - "./.env"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "logs:logs"
    depends_on:
      - database
    environment:
      - "DATABASE_HOSTNAME=database"
      - "DATABASE_PORT=27017"
  database:
    container_name: "goMuffin_database"
    image: "mongo:7.0.28"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}"
      - "MONGO_INITDB_DATABASE=${DATABASE_NAME}"

